name: Archive Blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  archive-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive full blog
        run: |
          wget -m -k -E -p -e robots=off https://walidcumo08-ahvpy.wordpress.com/

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add .
          # التحقق من وجود تغييرات قبل الرفع
          if ! git diff --quiet; then
            git commit -m "Update blog archive"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
